In [1]:
#导包
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# 1.Numpy的属性

In [2]:
#numpy的数组对象是ndarray,它是一个多维数组对象,它的元素类型是相同的,它的维度是固定的,它的大小是固定的,它的元素可以通过索引访问,它的元素可以通过切片访问,它的元素可以通过布尔索引访问,它的元素可以通过花式索引访问,它的元素可以通过广播机制访问,它的元素可以通过ufunc函数访问,它的元素可以通过通用函数访问,它的元素可以通过线性代数函数访问,它的元素可以通过统计函数访问,它的元素可以通过随机数函数访问,它的元素可以通过文件输入输出函数访问,它的元素可以通过数组操作函数访问,它的元素可以通过数组变形函数访问,它的元素可以通过数组连接函数访问,它的元素可以通过数组分割函数访问,它的元素可以通过数组排序函数访问,它的元素可以通过数组搜索函数访问,它的元素可以通过数组比较函数访问,它的元素可以通过数组逻辑函数访问,它的元素可以通过数组位运算函数访问,它的元素可以通过数组数学函数访问,它的元素可以通过数组统计函数访问,它的元素可以通过数组线性代数函数访问,它的元素可以通过数组随机数函数访问,它的元素可以通过数组文件输入输出函数访问,它的元素可以通过数组操作函数访问,它的元素可以通过数组变形函数访问,它的元素可以通过数组连接函数访问,它的元素可以通过数组分割函数访问,它的元素可以通过数组排序函数访问,它的元素可以通过数组搜索函数访问,它的元素可以通过数组比较函数访问,它的元素可以通过数组逻辑函数访问,它的元素可以通过数组位运算函数访问,它的元素可以通过数组数学函数访问.
arr1 = np.arange(15).reshape(3, 5)
print(arr1)
print(f'numpy的轴{arr1.ndim}')
print(f'numpy的形状{arr1.shape}')
print(f'numpy的元素类型{arr1.dtype}')
print(f'numpy的元素个数{arr1.size}')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
numpy的轴2
numpy的形状(3, 5)
numpy的元素类型int64
numpy的元素个数15


### 2.创建Numpy的ndarray对象

In [3]:
# --- IGNORE ---   array()函数
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#arange(起始值, 结束值, 步长，dtype = 类型)函数 = range()函数
arr3 = np.arange(0, 10, 1, dtype=np.float64)
print(arr3) 
print(type(arr3))
print(arr3.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>
float64


#### 2.2随机数生成ndarray对象

In [5]:
#random.rand()函数生成0-1之间的随机数【0,1)之间的随机数
arr4 = np.random.rand(3, 4)
print(arr4)

[[0.02189371 0.93017754 0.17837031 0.6504015 ]
 [0.76155675 0.1015175  0.19540067 0.11786843]
 [0.12348374 0.59527976 0.04930716 0.70449726]]


In [6]:
#2.random.randint(start, stop,size=(行,列))函数生成指定范围内的随机 *整数*[start, stop)
arr5 = np.random.randint(0, 10, size=(3, 4))
print(arr5)

[[6 9 1 7]
 [6 1 2 0]
 [0 8 6 5]]


In [7]:
#3.random.uniform(start, stop,size=(行,列))函数生成指定范围内的随机 *浮点数*[start, stop)
arr6 = np.random.uniform(0, 10, size=(3, 4))
print(arr6)

[[3.87265003 8.42174733 9.95602451 9.71246525]
 [2.23826412 6.1902895  4.53994176 2.82137142]
 [6.1949737  0.30987538 6.93363157 3.26097971]]


In [8]:
#4.random.randn(size=(行,列))函数生成标准正态分布的随机数
arr10 = np.random.randn(3, 4)
print(arr10)

[[ 0.15297261 -0.43701043  1.66861936  0.77932475]
 [ 0.40299992  0.25522265  0.71689458 -0.44372598]
 [-0.68051767  0.08545741 -0.92907871  0.04707594]]


#### 2.4numpy的类型转换

In [9]:
#astype()函数可以将数组的元素类型转换为指定的类型
print(arr3)
print(arr3.dtype)
arr7 = arr3.astype(np.float32)
print(arr7)
print(arr7.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float32


### 3.等比数列&等差数列

In [10]:
#3.1 logspace(start(充当10的指数), stop（充当10的指数）, num=元素个数,base = 基数(默认为10))函数生成等比数列
arr8 = np.logspace(0, 3, num=4)
print(arr8)

[   1.   10.  100. 1000.]


In [11]:
#3.2 linspace(start, stop, num=元素个数， endpoint=True(是否包含结束值),dtype=np.None )函数生成等差数列
arr9 = np.linspace(0, 10, num=5)
print(arr9)
print(arr9.dtype)

[ 0.   2.5  5.   7.5 10. ]
float64


# 4.numpy内置函数

In [12]:
# 4.1
arr11 = np.random.rand(3, 4) * 10
print(arr11)

[[4.61446908 6.42219499 4.7848537  9.19936442]
 [2.97818698 2.74016392 6.68638475 4.02498721]
 [1.25364313 9.90607424 6.18734003 7.13250994]]


In [13]:
#ceil()函数向上取整
arr12 = np.ceil(arr11)
print(arr12)

[[ 5.  7.  5. 10.]
 [ 3.  3.  7.  5.]
 [ 2. 10.  7.  8.]]


In [14]:
#floor()函数向下取整
arr13 = np.floor(arr11)
print(arr13)
print('-----------------------------')
#round()函数四舍五入
arr14 = np.round(arr11)
print(arr14)
print('-----------------------------')
#abs()函数取绝对值
arr15 = np.abs(arr11 - 5)
print(arr15)
print('-----------------------------')
#multiply(arr1,arr1)函数矩阵乘法(行列数要一致)
arr16 = np.multiply(arr11, arr11)
print(arr16)
print('-----------------------------')
print(arr11*arr11)#矩阵乘法(行列数要一致)同上
print('-----------------------------')
#where(判断，x,y)函数根据条件返回满足条件的元素的索引
arr17 = np.where(arr11 > 5,1,0)
print(arr17)

[[4. 6. 4. 9.]
 [2. 2. 6. 4.]
 [1. 9. 6. 7.]]
-----------------------------
[[ 5.  6.  5.  9.]
 [ 3.  3.  7.  4.]
 [ 1. 10.  6.  7.]]
-----------------------------
[[0.38553092 1.42219499 0.2151463  4.19936442]
 [2.02181302 2.25983608 1.68638475 0.97501279]
 [3.74635687 4.90607424 1.18734003 2.13250994]]
-----------------------------
[[21.29332486 41.24458847 22.8948249  84.62830566]
 [ 8.86959767  7.5084983  44.70774107 16.200522  ]
 [ 1.57162111 98.13030693 38.28317671 50.87269801]]
-----------------------------
[[21.29332486 41.24458847 22.8948249  84.62830566]
 [ 8.86959767  7.5084983  44.70774107 16.200522  ]
 [ 1.57162111 98.13030693 38.28317671 50.87269801]]
-----------------------------
[[0 1 0 1]
 [0 0 1 0]
 [0 1 1 1]]


## 5.统计函数

In [15]:
arr20 = np.arange(12).reshape(3, 4)
print(arr20)

#cumsum()函数计算数组元素的累积和
arr21 = np.cumsum(arr20)
print(arr21)

#sum()函数计算数组元素的和 axis=0按列求和，axis=1按行求和
arr22 = np.sum(arr20, axis=0)#按列求和
print(arr22)
arr23 = np.sum(arr20, axis=1)#按行求和
print(arr23)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[12 15 18 21]
[ 6 22 38]


In [16]:
#去重函数unique()函数返回数组中唯一的元素
list1 = ([[1, 2, 3], [4, 5, 6], [3,9,8]])
print(list1)
arr24 = np.unique(list1)
print(arr24)

[[1, 2, 3], [4, 5, 6], [3, 9, 8]]
[1 2 3 4 5 6 8 9]


In [17]:
#np.sort()函数对数组进行排序
arr25 = np.sort(list1)
print(arr25)
print('-----------------------------')
arr20.sort()
print(arr20)

[[1 2 3]
 [4 5 6]
 [3 8 9]]
-----------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
#乘积  行列数不一致
#@   or  dot()函数矩阵乘法
list2 = np.array([[1, 2], [3, 4], [5, 6]])
list3 = np.array([[1, 2, 3], [4, 5, 6]])
print(list2 @ list3)
print(list2.dot(list3))
print(np.dot(list2, list3))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


# 6.Pandas

### 6.1 Series对象

In [19]:
s1 = pd.Series([1,2,3,4,5])#默认自增索引
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [20]:
s2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])#自定义索引
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [21]:
#字典 and 元组创建Series对象

s3 = pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})#字典创建Series对象
print(s3)
s4 = pd.Series((1,2,3,4,5), index=['a','b','c','d','e'])#元组创建Series对象
print(s4)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [22]:
#使用numpy-->创建series对象
s5 = pd.Series(np.arange(1,6))
print(s5)

0    1
1    2
2    3
3    4
4    5
dtype: int64



### Series 对象的属性

In [23]:
s6 = pd.Series(data = [i for i in range(6)], index=[i for i in 'ABCDEF'])
print(s6)

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64


In [24]:
print(s6['A'])#通过索引访问元素
print(s6.values)#通过values属性访问值
print(s6.index)#通过index属性访问索引
s6['D'] = 66#通过索引修改元素值
print(s6)

0
[0 1 2 3 4 5]
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
A     0
B     1
C     2
D    66
E     4
F     5
dtype: int64


# *DataFrame

In [25]:
#字典+列表实现
info = {
    'name':['张三','李四','王五','赵六','钱七'],
    'age':[18,19,20,21,22],
    'city':['北京','上海','广州','深圳','杭州']
}

df1 = pd.DataFrame(info)
print(df1)

  name  age city
0   张三   18   北京
1   李四   19   上海
2   王五   20   广州
3   赵六   21   深圳
4   钱七   22   杭州


In [26]:
#列表+元组实现
data = [('张三', 18, '北京'),
        ('李四', 19, '上海'),
        ('王五', 20, '广州'),
        ('赵六', 21, '深圳'),
        ('钱七', 22, '杭州')]
df2 = pd.DataFrame(data, columns=['name', 'age', 'city'])
print(df2)

  name  age city
0   张三   18   北京
1   李四   19   上海
2   王五   20   广州
3   赵六   21   深圳
4   钱七   22   杭州


###  -----简单案例-----

In [27]:
#生成10名学生，5门功课的成绩（40-100之间的随机整数）
score_df = pd.DataFrame(np.random.randint(40,101,size = (10,5)),columns = ['语文','数学','英语','体育','音乐'])
index_names = ['Student'+str(i) for i in range(score_df.shape[0])]
score_df.index = index_names
print(score_df)

          语文  数学  英语   体育  音乐
Student0  56  43  78   78  67
Student1  55  94  82   41  67
Student2  95  81  59   40  99
Student3  88  63  85   73  79
Student4  71  84  86   99  65
Student5  59  73  63   87  91
Student6  63  45  83  100  82
Student7  98  97  99   84  76
Student8  82  77  75   76  91
Student9  54  66  83   63  63


In [28]:
# head()函数返回DataFrame的前n行，默认为5行
print(score_df.head())
print('-----------------------------')
print(score_df.head(3))#返回前3行

          语文  数学  英语  体育  音乐
Student0  56  43  78  78  67
Student1  55  94  82  41  67
Student2  95  81  59  40  99
Student3  88  63  85  73  79
Student4  71  84  86  99  65
-----------------------------
          语文  数学  英语  体育  音乐
Student0  56  43  78  78  67
Student1  55  94  82  41  67
Student2  95  81  59  40  99


In [29]:
# tail()函数返回DataFrame的后n行，默认为5行
print(score_df.tail())
print('-----------------------------')
print(score_df.tail(3))#返回后3行

          语文  数学  英语   体育  音乐
Student5  59  73  63   87  91
Student6  63  45  83  100  82
Student7  98  97  99   84  76
Student8  82  77  75   76  91
Student9  54  66  83   63  63
-----------------------------
          语文  数学  英语  体育  音乐
Student7  98  97  99  84  76
Student8  82  77  75  76  91
Student9  54  66  83  63  63


In [30]:
#info()函数查看DataFrame的基本信息
score_df.info()
print('-----------------------------')
#describe()函数查看DataFrame的统计信息
score_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Student0 to Student9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int32
 1   数学      10 non-null     int32
 2   英语      10 non-null     int32
 3   体育      10 non-null     int32
 4   音乐      10 non-null     int32
dtypes: int32(5)
memory usage: 280.0+ bytes
-----------------------------


,语文,数学,英语,体育,音乐
count,10.000000,10.000000,10.00000,10.000000,10.00000
mean,72.100000,72.300000,79.30000,74.100000,78.00000
std,17.259136,18.397162,11.53786,20.967965,12.63153
min,54.000000,43.000000,59.00000,40.000000,63.00000
25%,56.750000,63.750000,75.75000,65.500000,67.00000
50%,67.000000,75.000000,82.50000,77.000000,77.50000
75%,86.500000,83.250000,84.50000,86.250000,88.75000
max,98.000000,97.000000,99.00000,100.000000,99.00000


In [31]:
#生成10名学生，5门功课的成绩（40-100之间的随机整数）
score_df = pd.DataFrame(np.random.randint(40,101,size = (10,5)),columns = ['语文','数学','英语','体育','音乐'])
index_names = ['Student'+str(i) for i in range(score_df.shape[0])]
score_df.index = index_names
print(score_df)#显示原DataFrame的内容
print('-----------------------------')
#reset_index()函数重置索引
score_df.reset_index(drop=True, inplace=True)
print(score_df)

          语文  数学  英语  体育  音乐
Student0  69  43  46  45  49
Student1  48  50  70  47  41
Student2  41  79  57  98  78
Student3  80  77  81  70  55
Student4  43  52  59  41  90
Student5  64  81  70  57  40
Student6  62  63  91  65  80
Student7  70  82  97  85  96
Student8  90  64  88  96  99
Student9  53  70  84  68  51
-----------------------------
   语文  数学  英语  体育  音乐
0  69  43  46  45  49
1  48  50  70  47  41
2  41  79  57  98  78
3  80  77  81  70  55
4  43  52  59  41  90
5  64  81  70  57  40
6  62  63  91  65  80
7  70  82  97  85  96
8  90  64  88  96  99
9  53  70  84  68  51
