In [1]:
#导包
import numpy as np
import pandas as pd
import matplotlib.pyplot

# 1.Numpy的属性

In [2]:
#numpy的数组对象是ndarray,它是一个多维数组对象,它的元素类型是相同的,它的维度是固定的,它的大小是固定的,它的元素可以通过索引访问,它的元素可以通过切片访问,它的元素可以通过布尔索引访问,它的元素可以通过花式索引访问,它的元素可以通过广播机制访问,它的元素可以通过ufunc函数访问,它的元素可以通过通用函数访问,它的元素可以通过线性代数函数访问,它的元素可以通过统计函数访问,它的元素可以通过随机数函数访问,它的元素可以通过文件输入输出函数访问,它的元素可以通过数组操作函数访问,它的元素可以通过数组变形函数访问,它的元素可以通过数组连接函数访问,它的元素可以通过数组分割函数访问,它的元素可以通过数组排序函数访问,它的元素可以通过数组搜索函数访问,它的元素可以通过数组比较函数访问,它的元素可以通过数组逻辑函数访问,它的元素可以通过数组位运算函数访问,它的元素可以通过数组数学函数访问,它的元素可以通过数组统计函数访问,它的元素可以通过数组线性代数函数访问,它的元素可以通过数组随机数函数访问,它的元素可以通过数组文件输入输出函数访问,它的元素可以通过数组操作函数访问,它的元素可以通过数组变形函数访问,它的元素可以通过数组连接函数访问,它的元素可以通过数组分割函数访问,它的元素可以通过数组排序函数访问,它的元素可以通过数组搜索函数访问,它的元素可以通过数组比较函数访问,它的元素可以通过数组逻辑函数访问,它的元素可以通过数组位运算函数访问,它的元素可以通过数组数学函数访问.
arr1 = np.arange(15).reshape(3, 5)
print(arr1)
print(f'numpy的轴{arr1.ndim}')
print(f'numpy的形状{arr1.shape}')
print(f'numpy的元素类型{arr1.dtype}')
print(f'numpy的元素个数{arr1.size}')


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
numpy的轴2
numpy的形状(3, 5)
numpy的元素类型int64
numpy的元素个数15


### 2.创建Numpy的ndarray对象

In [3]:
# --- IGNORE ---   array()函数
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2)
print(type(arr2))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
#arange(起始值, 结束值, 步长，dtype = 类型)函数 = range()函数
arr3 = np.arange(0, 10, 1, dtype=np.float64)
print(arr3) 
print(type(arr3))
print(arr3.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
<class 'numpy.ndarray'>
float64


#### 2.2随机数生成ndarray对象

In [5]:
#random.rand()函数生成0-1之间的随机数【0,1)之间的随机数
arr4 = np.random.rand(3, 4)
print(arr4)

[[0.5912166  0.32260486 0.71175639 0.62961318]
 [0.468354   0.75899226 0.67699486 0.78832002]
 [0.59014178 0.95063293 0.78314445 0.8173838 ]]


In [6]:
#2.random.randint(start, stop,size=(行,列))函数生成指定范围内的随机 *整数*[start, stop)
arr5 = np.random.randint(0, 10, size=(3, 4))
print(arr5)

[[5 3 1 6]
 [5 9 0 6]
 [4 6 5 6]]


In [7]:
#3.random.uniform(start, stop,size=(行,列))函数生成指定范围内的随机 *浮点数*[start, stop)
arr6 = np.random.uniform(0, 10, size=(3, 4))
print(arr6)

[[8.028122   1.43633342 9.57899019 9.23418399]
 [4.79989363 8.22048424 4.50796301 9.8660127 ]
 [6.23802368 4.69863876 8.4148529  3.18643071]]


In [8]:
#4.random.randn(size=(行,列))函数生成标准正态分布的随机数
arr10 = np.random.randn(3, 4)
print(arr10)

[[ 0.08950827 -0.16460637 -0.21341901 -0.82460707]
 [-1.73892103  0.04350836 -0.55922759  0.20457362]
 [ 0.52031642 -0.23622647  0.08119011  0.38683927]]


#### 2.4numpy的类型转换

In [9]:
#astype()函数可以将数组的元素类型转换为指定的类型
print(arr3)
print(arr3.dtype)
arr7 = arr3.astype(np.float32)
print(arr7)
print(arr7.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float32


### 3.等比数列&等差数列

In [10]:
#3.1 logspace(start(充当10的指数), stop（充当10的指数）, num=元素个数,base = 基数(默认为10))函数生成等比数列
arr8 = np.logspace(0, 3, num=4)
print(arr8)

[   1.   10.  100. 1000.]


In [11]:
#3.2 linspace(start, stop, num=元素个数， endpoint=True(是否包含结束值),dtype=np.None )函数生成等差数列
arr9 = np.linspace(0, 10, num=5)
print(arr9)
print(arr9.dtype)

[ 0.   2.5  5.   7.5 10. ]
float64


# 4.numpy内置函数

In [12]:
# 4.1
arr11 = np.random.rand(3, 4) * 10
print(arr11)

[[7.49229144 1.33031261 4.00884299 9.63851048]
 [4.72406025 1.18273871 2.32870101 9.1467827 ]
 [8.95663321 6.10958311 0.27232486 7.55321574]]


In [13]:
#ceil()函数向上取整
arr12 = np.ceil(arr11)
print(arr12)

[[ 8.  2.  5. 10.]
 [ 5.  2.  3. 10.]
 [ 9.  7.  1.  8.]]


In [14]:
#floor()函数向下取整
arr13 = np.floor(arr11)
print(arr13)
print('-----------------------------')
#round()函数四舍五入
arr14 = np.round(arr11)
print(arr14)
print('-----------------------------')
#abs()函数取绝对值
arr15 = np.abs(arr11 - 5)
print(arr15)
print('-----------------------------')
#multiply(arr1,arr1)函数矩阵乘法(行列数要一致)
arr16 = np.multiply(arr11, arr11)
print(arr16)
print('-----------------------------')
print(arr11*arr11)#矩阵乘法(行列数要一致)同上
print('-----------------------------')
#where(判断，x,y)函数根据条件返回满足条件的元素的索引
arr17 = np.where(arr11 > 5,1,0)
print(arr17)

[[7. 1. 4. 9.]
 [4. 1. 2. 9.]
 [8. 6. 0. 7.]]
-----------------------------
[[ 7.  1.  4. 10.]
 [ 5.  1.  2.  9.]
 [ 9.  6.  0.  8.]]
-----------------------------
[[2.49229144 3.66968739 0.99115701 4.63851048]
 [0.27593975 3.81726129 2.67129899 4.1467827 ]
 [3.95663321 1.10958311 4.72767514 2.55321574]]
-----------------------------
[[5.61344310e+01 1.76973164e+00 1.60708222e+01 9.29008842e+01]
 [2.23167453e+01 1.39887086e+00 5.42284838e+00 8.36636337e+01]
 [8.02212784e+01 3.73270058e+01 7.41608291e-02 5.70510679e+01]]
-----------------------------
[[5.61344310e+01 1.76973164e+00 1.60708222e+01 9.29008842e+01]
 [2.23167453e+01 1.39887086e+00 5.42284838e+00 8.36636337e+01]
 [8.02212784e+01 3.73270058e+01 7.41608291e-02 5.70510679e+01]]
-----------------------------
[[1 0 0 1]
 [0 0 0 1]
 [1 1 0 1]]


## 5.统计函数

In [15]:
arr20 = np.arange(12).reshape(3, 4)
print(arr20)

#cumsum()函数计算数组元素的累积和
arr21 = np.cumsum(arr20)
print(arr21)

#sum()函数计算数组元素的和 axis=0按列求和，axis=1按行求和
arr22 = np.sum(arr20, axis=0)#按列求和
print(arr22)
arr23 = np.sum(arr20, axis=1)#按行求和
print(arr23)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  3  6 10 15 21 28 36 45 55 66]
[12 15 18 21]
[ 6 22 38]


In [16]:
#去重函数unique()函数返回数组中唯一的元素
list1 = ([[1, 2, 3], [4, 5, 6], [3,9,8]])
print(list1)
arr24 = np.unique(list1)
print(arr24)

[[1, 2, 3], [4, 5, 6], [3, 9, 8]]
[1 2 3 4 5 6 8 9]


In [17]:
#np.sort()函数对数组进行排序
arr25 = np.sort(list1)
print(arr25)
print('-----------------------------')
arr20.sort()
print(arr20)

[[1 2 3]
 [4 5 6]
 [3 8 9]]
-----------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
#乘积  行列数不一致
#@   or  dot()函数矩阵乘法
list2 = np.array([[1, 2], [3, 4], [5, 6]])
list3 = np.array([[1, 2, 3], [4, 5, 6]])
print(list2 @ list3)
print(list2.dot(list3))
print(np.dot(list2, list3))

[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


# 6.Pandas

### 6.1 Series对象

In [19]:
s1 = pd.Series([1,2,3,4,5])#默认自增索引
print(s1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [20]:
s2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])#自定义索引
print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [21]:
#字典 and 元组创建Series对象

s3 = pd.Series({'a':1,'b':2,'c':3,'d':4,'e':5})#字典创建Series对象
print(s3)
s4 = pd.Series((1,2,3,4,5), index=['a','b','c','d','e'])#元组创建Series对象
print(s4)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64


In [22]:
#使用numpy-->创建series对象
s5 = pd.Series(np.arange(1,6))
print(s5)

0    1
1    2
2    3
3    4
4    5
dtype: int64



### Series 对象的属性

In [23]:
s6 = pd.Series(data = [i for i in range(6)], index=[i for i in 'ABCDEF'])
print(s6)

A    0
B    1
C    2
D    3
E    4
F    5
dtype: int64


In [24]:
print(s6['A'])#通过索引访问元素
print(s6.values)#通过values属性访问值
print(s6.index)#通过index属性访问索引
s6['D'] = 66#通过索引修改元素值
print(s6)

0
[0 1 2 3 4 5]
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')
A     0
B     1
C     2
D    66
E     4
F     5
dtype: int64


# *DataFrame

In [25]:
#字典+列表实现
info = {
    'name':['张三','李四','王五','赵六','钱七'],
    'age':[18,19,20,21,22],
    'city':['北京','上海','广州','深圳','杭州']
}

df1 = pd.DataFrame(info)
print(df1)

  name  age city
0   张三   18   北京
1   李四   19   上海
2   王五   20   广州
3   赵六   21   深圳
4   钱七   22   杭州


In [26]:
#列表+元组实现
data = [('张三', 18, '北京'),
        ('李四', 19, '上海'),
        ('王五', 20, '广州'),
        ('赵六', 21, '深圳'),
        ('钱七', 22, '杭州')]
df2 = pd.DataFrame(data, columns=['name', 'age', 'city'])
print(df2)

  name  age city
0   张三   18   北京
1   李四   19   上海
2   王五   20   广州
3   赵六   21   深圳
4   钱七   22   杭州


###  -----简单案例-----

In [27]:
#生成10名学生，5门功课的成绩（40-100之间的随机整数）
score_df = pd.DataFrame(np.random.randint(40,101,size = (10,5)),columns = ['语文','数学','英语','体育','音乐'])
index_names = ['Student'+str(i) for i in range(score_df.shape[0])]
score_df.index = index_names
print(score_df)

          语文  数学   英语  体育   音乐
Student0  85  67   68  45   57
Student1  66  98   80  63   90
Student2  78  48   56  93   44
Student3  56  98   82  89   67
Student4  60  98   95  58  100
Student5  51  49   52  73  100
Student6  76  71  100  63   75
Student7  62  93   53  66   51
Student8  92  61   75  51   45
Student9  64  50   72  75   92


In [28]:
# head()函数返回DataFrame的前n行，默认为5行
print(score_df.head())
print('-----------------------------')
print(score_df.head(3))#返回前3行

          语文  数学  英语  体育   音乐
Student0  85  67  68  45   57
Student1  66  98  80  63   90
Student2  78  48  56  93   44
Student3  56  98  82  89   67
Student4  60  98  95  58  100
-----------------------------
          语文  数学  英语  体育  音乐
Student0  85  67  68  45  57
Student1  66  98  80  63  90
Student2  78  48  56  93  44


In [29]:
# tail()函数返回DataFrame的后n行，默认为5行
print(score_df.tail())
print('-----------------------------')
print(score_df.tail(3))#返回后3行

          语文  数学   英语  体育   音乐
Student5  51  49   52  73  100
Student6  76  71  100  63   75
Student7  62  93   53  66   51
Student8  92  61   75  51   45
Student9  64  50   72  75   92
-----------------------------
          语文  数学  英语  体育  音乐
Student7  62  93  53  66  51
Student8  92  61  75  51  45
Student9  64  50  72  75  92


In [30]:
#info()函数查看DataFrame的基本信息
score_df.info()
print('-----------------------------')
#describe()函数查看DataFrame的统计信息
score_df.describe()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, Student0 to Student9
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   语文      10 non-null     int32
 1   数学      10 non-null     int32
 2   英语      10 non-null     int32
 3   体育      10 non-null     int32
 4   音乐      10 non-null     int32
dtypes: int32(5)
memory usage: 280.0+ bytes
-----------------------------


,语文,数学,英语,体育,音乐
count,10.000000,10.000000,10.000000,10.00000,10.000000
mean,69.000000,73.300000,73.300000,67.60000,72.100000
std,13.216152,21.571844,16.673665,15.31303,22.372851
min,51.000000,48.000000,52.000000,45.00000,44.000000
25%,60.500000,52.750000,59.000000,59.25000,52.500000
50%,65.000000,69.000000,73.500000,64.50000,71.000000
75%,77.500000,96.750000,81.500000,74.50000,91.500000
max,92.000000,98.000000,100.000000,93.00000,100.000000


In [31]:
#生成10名学生，5门功课的成绩（40-100之间的随机整数）
score_df = pd.DataFrame(np.random.randint(40,101,size = (10,5)),columns = ['语文','数学','英语','体育','音乐'])
index_names = ['Student'+str(i) for i in range(score_df.shape[0])]
score_df.index = index_names
print(score_df)#显示原DataFrame的内容
print('-----------------------------')
#reset_index()函数重置索引
score_df.reset_index(drop=True, inplace=True)
print(score_df)

          语文  数学  英语  体育  音乐
Student0  77  63  90  69  42
Student1  49  47  87  86  73
Student2  44  95  67  49  58
Student3  61  65  72  55  56
Student4  63  46  41  41  89
Student5  59  45  98  50  40
Student6  80  78  62  47  79
Student7  85  53  40  79  97
Student8  42  55  57  60  82
Student9  77  95  83  54  54
-----------------------------
   语文  数学  英语  体育  音乐
0  77  63  90  69  42
1  49  47  87  86  73
2  44  95  67  49  58
3  61  65  72  55  56
4  63  46  41  41  89
5  59  45  98  50  40
6  80  78  62  47  79
7  85  53  40  79  97
8  42  55  57  60  82
9  77  95  83  54  54
